import Foundation

// Codable mirrors of Grimmory's `org.booklore.app.dto` types.
//
// Grimmory annotates these with @JsonInclude(NON_NULL), so any field can be
// absent from the payload — every property here is optional except the ones
// the server always populates. Verified against grimmory-tools/grimmory@develop.

struct AppPageResponse<T: Decodable & Sendable>: Decodable, Sendable {
    let content: [T]
    let page: Int
    let size: Int
    let totalElements: Int
    let totalPages: Int
    let hasNext: Bool
    let hasPrevious: Bool
}

struct AppBookSummary: Decodable, Sendable, Identifiable, Hashable {
    let id: Int64
    let title: String?
    let authors: [String]?
    let thumbnailUrl: String?
    let readStatus: String?
    let personalRating: Int?
    let seriesName: String?
    let seriesNumber: Float?
    let libraryId: Int64?
    let addedOn: Date?
    let lastReadTime: Date?
    let readProgress: Float?
    let primaryFileId: Int64?
    let primaryFileType: String?
    let primaryFileName: String?
    let coverUpdatedOn: Date?
    let isPhysical: Bool?
    let publisher: String?
    let categories: [String]?
    let tags: [String]?
    let language: String?
    let pageCount: Int?
    let fileSizeKb: Int64?
}

struct AppBookFile: Decodable, Sendable, Identifiable, Hashable {
    let id: Int64
    let bookId: Int64?
    let fileName: String?
    let bookType: String?
    let fileSizeKb: Int64?
    let fileExtension: String?
    let isBook: Bool?
    let isPrimary: Bool?
    let folderBased: Bool?

    private enum CodingKeys: String, CodingKey {
        case id, bookId, fileName, bookType, fileSizeKb, folderBased
        case fileExtension = "extension"
        case isBook, book
        case isPrimary, primary
    }

    init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(Int64.self, forKey: .id)
        bookId = try c.decodeIfPresent(Int64.self, forKey: .bookId)
        fileName = try c.decodeIfPresent(String.self, forKey: .fileName)
        bookType = try c.decodeIfPresent(String.self, forKey: .bookType)
        fileSizeKb = try c.decodeIfPresent(Int64.self, forKey: .fileSizeKb)
        fileExtension = try c.decodeIfPresent(String.self, forKey: .fileExtension)
        folderBased = try c.decodeIfPresent(Bool.self, forKey: .folderBased)
        isBook = try c.decodeBoolEitherSpelling(.isBook, stripped: .book)
        isPrimary = try c.decodeBoolEitherSpelling(.isPrimary, stripped: .primary)
    }
}

struct EpubProgress: Decodable, Sendable, Hashable {
    /// An EPUB CFI, generated by foliate-js. Stored server-side as
    /// `BookFileProgress.positionData`.
    let cfi: String?
    /// Spine href, stored as `BookFileProgress.positionHref`.
    let href: String?
    let percentage: Float?
    let updatedAt: Date?
}

struct AppBookDetail: Decodable, Sendable, Identifiable {
    let id: Int64
    let title: String?
    let authors: [String]?
    let thumbnailUrl: String?
    let readStatus: String?
    let personalRating: Int?
    let seriesName: String?
    let seriesNumber: Float?
    let libraryId: Int64?
    let libraryName: String?
    let addedOn: Date?
    let lastReadTime: Date?
    let subtitle: String?
    let description: String?
    let categories: [String]?
    let publisher: String?
    let pageCount: Int?
    let isbn13: String?
    let language: String?
    let readProgress: Float?
    let primaryFileType: String?
    let fileTypes: [String]?
    let files: [AppBookFile]?
    let coverUpdatedOn: Date?
    let isPhysical: Bool?
    let epubProgress: EpubProgress?
}

struct AppBookProgressResponse: Decodable, Sendable {
    let readProgress: Float?
    let readStatus: String?
    let lastReadTime: Date?
    let epubProgress: EpubProgress?
}

struct AppLibrarySummary: Decodable, Sendable, Identifiable, Hashable {
    let id: Int64
    let name: String?
    let icon: String?
    let bookCount: Int
}

struct AppShelfSummary: Decodable, Sendable, Identifiable, Hashable {
    let id: Int64
    let name: String?
    let icon: String?
    let bookCount: Int
}

struct AppUserInfo: Decodable, Sendable {
    let isAdmin: Bool
    let canUpload: Bool
    let canDownload: Bool
    let canAccessBookdrop: Bool
    let maxFileUploadSizeMb: Int

    private enum CodingKeys: String, CodingKey {
        case isAdmin, admin
        case canUpload, canDownload, canAccessBookdrop, maxFileUploadSizeMb
    }

    init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        isAdmin = try c.decodeBoolEitherSpelling(.isAdmin, stripped: .admin) ?? false
        canUpload = try c.decodeIfPresent(Bool.self, forKey: .canUpload) ?? false
        canDownload = try c.decodeIfPresent(Bool.self, forKey: .canDownload) ?? false
        canAccessBookdrop = try c.decodeIfPresent(Bool.self, forKey: .canAccessBookdrop) ?? false
        maxFileUploadSizeMb = try c.decodeIfPresent(Int.self, forKey: .maxFileUploadSizeMb) ?? 0
    }
}

struct AppMagicShelfSummary: Decodable, Sendable, Identifiable, Hashable {
    let id: Int64
    let name: String?
    let icon: String?
    let iconType: String?
    let publicShelf: Bool?

    private enum CodingKeys: String, CodingKey {
        case id, name, icon, iconType
        case publicShelf, isPublicShelf
    }

    init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(Int64.self, forKey: .id)
        name = try c.decodeIfPresent(String.self, forKey: .name)
        icon = try c.decodeIfPresent(String.self, forKey: .icon)
        iconType = try c.decodeIfPresent(String.self, forKey: .iconType)
        publicShelf = try c.decodeBoolEitherSpelling(.isPublicShelf, stripped: .publicShelf)
    }
}

struct SeriesCoverBook: Decodable, Sendable, Hashable {
    let bookId: Int64?
    let coverUpdatedOn: Date?
}

/// Series are keyed by name, not id — the server has no series entity.
struct AppSeriesSummary: Decodable, Sendable, Identifiable, Hashable {
    var id: String {
        seriesName
    }

    let seriesName: String
    let bookCount: Int
    let seriesTotal: Int?
    let authors: [String]?
    let booksRead: Int
    let latestAddedOn: Date?
    let coverBooks: [SeriesCoverBook]?
}

struct AppAuthorSummary: Decodable, Sendable, Identifiable, Hashable {
    let id: Int64
    let name: String?
    let bookCount: Int
    let hasPhoto: Bool?

    private enum CodingKeys: String, CodingKey {
        case id, name, bookCount
        case hasPhoto
    }

    init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(Int64.self, forKey: .id)
        name = try c.decodeIfPresent(String.self, forKey: .name)
        bookCount = try c.decodeIfPresent(Int.self, forKey: .bookCount) ?? 0
        hasPhoto = try c.decodeIfPresent(Bool.self, forKey: .hasPhoto)
    }
}
